### ISSUE TITLE
Can I use Elloreas to assemble a large and high heterozygous rate genome?

### ISSUE THREAD

**Issue by xiekunwhy** [shelkmike/Elloreas#1]
Hi,

Can I use Elloreas to  assemble a large (>1G) and high heterozygous rate (may be>5%) genome lilke plants or animals nuclear genome?

Best wishes,
Kun

**Comment by shelkmike** [comment]
Hi. Theoretically, you can, but I don't recommend it for two reasons:
1) Elloreas is rather slow.
2) Elloreas is intended first and foremost for local assembly. I mean, if you assembled a genome by some de novo assembler, and then you want to assemble some place where that assembler failed, this is the task for Elloreas.

What you probably want is a "de novo" assembly. If you have long reads, I recommend tools like [Falcon](https://github.com/PacificBiosciences/pb-assembly), [Canu ](https://github.com/marbl/canu) or [Flye](https://github.com/fenderglass/Flye).
